[shell.variables]
os = "arch"

[shell.variables.installers.pacman.commands]
install = "sudo pacman -Syu --noconfirm"
uninstall = "sudo pacman -Rns --noconfirm"

[shell.variables.installers.pacman]
packages = ["nano", "powerline", "bash", "zsh", "git"]

[shell.variables.installers.pamac.commands]
install = "sudo pamac install --no-confirm"
uninstall = "sudo pamac remove --no-confirm"

[shell.variables.installers.pamac]
packages = []
