export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=white,bold'

source $ZSH/oh-my-zsh.sh

plugins=(
  git
  docker
  composer
  sudo
  npm
  zsh-autosuggestions
  zsh-syntax-highlighting
  dotnet
  pipenv
)

[[ -f ~/.profile ]] && . ~/.profile

# Загрузите комплитаут
autoload -Uz compinit && compinit
