[helpers]
pre_script_runner = ".dotter/helpers/pre-script-runner.rhai"
package_installer = ".dotter/helpers/package-installer.rhai"
post_script_runner = ".dotter/helpers/post-script-runner.rhai"
active_packages_filter = ".dotter/helpers/active-packages-filter.rhai"

[shell.files]
".dotter/scripts" = { target = "", type = "template" }
"shell/profile" = { target = "~/.profile", type = "template" }

[shell.variables]
install = true
uninstall = true

[nano]
depends = ["shell"]

[openssh]
depends = ["shell"]

[openssh.files]
"openssh/ssh-agent.service" = "~/.config/systemd/user/ssh-agent.service"


[openssh-server]
depends = ["shell"]

[openssh-server.files]
"openssh/ssh-agent.service" = "~/.config/systemd/user/ssh-agent.service"

[bash]
depends = ["shell"]

[bash.files]
"bash/bash_profile" = { target = "~/.bash_profile", type = "symbolic" }

[bash.variables]

[zsh]
depends = ["shell"]

[zsh.files]
"zsh/zprofile" = "~/.zprofile"

[powerline]
depends = ["zsh"]

[oh-my-zsh]
depends = ["zsh", "powerline"]

[oh-my-zsh.files]
"oh-my-zsh/zshrc" = { target = "~/.zshrc", type = "symbolic" }

[zsh-autosuggestions]
depends = ["oh-my-zsh"]

[zsh-syntax-highlighting]
depends = ["oh-my-zsh"]

[snapd]
depends = ["shell"]

[yay]
depends = ["shell"]

[git]
depends = ["shell"]

[git.variables]
git_email = "serg.shehov@tutanota.com"
git_name = "Zyrakq"

[git.files]
"git/gitconfig" = { target = "~/.gitconfig", type = "template" }

[settings]
default_target_type = "automatic"
