# Pc
includes = [".dotter/includes/manjaro.toml"]

packages = [
    "nano",
    "bash",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
    "git",
    "openssh",
]

[files]

[variables]
managers = ["pacman", "pamac"]
