# Tess (ubuntu) selectel-moscow
includes = [".dotter/includes/ubuntu.toml"]

packages = [
    "nano",
    "bash",
    "zsh-autosuggestions",
    "git",
    "snapd",
    "openssh-server",
]

[files]

[variables]
managers = ["apt"]
